### ISSUE TITLE
[todo] add support for callbacks

### ISSUE THREAD

**Issue by Armael** [logsem/melocoton#2]
WIP in the https://github.com/logsem/melocoton/tree/callbacks branch.

- [x] refactor the wrapper operational semantics to act as a wrapper on ML programs (instead of C programs as currently). Done in the branch.
- [x] add a callbacks primitive in the operational semantics. Done in the branch.
- [x] update the state interpretation, and proofs...
- [x] merge the callbacks branch into the main branch
