### ISSUE TITLE
[todo] add a couple missing basic primitives

### ISSUE THREAD

**Issue by Armael** [logsem/melocoton#3]
- [x] add a primitive to get the tag of a block
- [x] add a primitive to get a block length (only makes sense for structured blocks, not e.g. closure blocks)
- [x] add a primitive to check whether something is a block or a number (i.e. is_Block)
